package com.example.demo.entity;

public class CrProductInfoWithBLOBs extends CrProductInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.DESCRIPTION
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.COMPANY_DESC
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String companyDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.COMPANY_TEAM
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String companyTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.INTELLECTUAL_PROPERTY
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String intellectualProperty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.DESCRIPTION
     *
     * @return the value of cr_product_info.DESCRIPTION
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.DESCRIPTION
     *
     * @param description the value for cr_product_info.DESCRIPTION
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.COMPANY_DESC
     *
     * @return the value of cr_product_info.COMPANY_DESC
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getCompanyDesc() {
        return companyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.COMPANY_DESC
     *
     * @param companyDesc the value for cr_product_info.COMPANY_DESC
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setCompanyDesc(String companyDesc) {
        this.companyDesc = companyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.COMPANY_TEAM
     *
     * @return the value of cr_product_info.COMPANY_TEAM
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getCompanyTeam() {
        return companyTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.COMPANY_TEAM
     *
     * @param companyTeam the value for cr_product_info.COMPANY_TEAM
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setCompanyTeam(String companyTeam) {
        this.companyTeam = companyTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.INTELLECTUAL_PROPERTY
     *
     * @return the value of cr_product_info.INTELLECTUAL_PROPERTY
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getIntellectualProperty() {
        return intellectualProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.INTELLECTUAL_PROPERTY
     *
     * @param intellectualProperty the value for cr_product_info.INTELLECTUAL_PROPERTY
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setIntellectualProperty(String intellectualProperty) {
        this.intellectualProperty = intellectualProperty;
    }
}