package com.example.demo.entity;

import java.util.Date;

public class CrProductInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.ID
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.NAME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.COMPANY_NAME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.IMAGE_SRC
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String imageSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.MEMBER_NUMBER
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String memberNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.USER_ID
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.AREA
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.INDUSTRY_NATURE_CODE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String industryNatureCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.INDUSTRY_NATURE_NAME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String industryNatureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.LAST_YEAR_TURNOVER
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Integer lastYearTurnover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.IS_PROFITABLE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Boolean isProfitable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.FINANCING
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String financing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.PRODUCT_VALUATION
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Integer productValuation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.FINANCING_PROCESS
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String financingProcess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.DILUTION_RATIO
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Integer dilutionRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.FINANCING_AMOUNT
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Integer financingAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.CREDIT_RISK
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String creditRisk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.BORROWING_COST
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String borrowingCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.BORROWING_CYCLE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String borrowingCycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.VERIFY_DESCRIPTION
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String verifyDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.STATUS
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.CREATE_TIME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.UPDATE_TIME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.IS_DELETE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.IS_FEATURE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private Boolean isFeature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.TAGS
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_product_info.OPERATOR
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.ID
     *
     * @return the value of cr_product_info.ID
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.ID
     *
     * @param id the value for cr_product_info.ID
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.NAME
     *
     * @return the value of cr_product_info.NAME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.NAME
     *
     * @param name the value for cr_product_info.NAME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.COMPANY_NAME
     *
     * @return the value of cr_product_info.COMPANY_NAME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.COMPANY_NAME
     *
     * @param companyName the value for cr_product_info.COMPANY_NAME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.IMAGE_SRC
     *
     * @return the value of cr_product_info.IMAGE_SRC
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getImageSrc() {
        return imageSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.IMAGE_SRC
     *
     * @param imageSrc the value for cr_product_info.IMAGE_SRC
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setImageSrc(String imageSrc) {
        this.imageSrc = imageSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.MEMBER_NUMBER
     *
     * @return the value of cr_product_info.MEMBER_NUMBER
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getMemberNumber() {
        return memberNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.MEMBER_NUMBER
     *
     * @param memberNumber the value for cr_product_info.MEMBER_NUMBER
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setMemberNumber(String memberNumber) {
        this.memberNumber = memberNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.USER_ID
     *
     * @return the value of cr_product_info.USER_ID
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.USER_ID
     *
     * @param userId the value for cr_product_info.USER_ID
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.AREA
     *
     * @return the value of cr_product_info.AREA
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.AREA
     *
     * @param area the value for cr_product_info.AREA
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.INDUSTRY_NATURE_CODE
     *
     * @return the value of cr_product_info.INDUSTRY_NATURE_CODE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getIndustryNatureCode() {
        return industryNatureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.INDUSTRY_NATURE_CODE
     *
     * @param industryNatureCode the value for cr_product_info.INDUSTRY_NATURE_CODE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setIndustryNatureCode(String industryNatureCode) {
        this.industryNatureCode = industryNatureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.INDUSTRY_NATURE_NAME
     *
     * @return the value of cr_product_info.INDUSTRY_NATURE_NAME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getIndustryNatureName() {
        return industryNatureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.INDUSTRY_NATURE_NAME
     *
     * @param industryNatureName the value for cr_product_info.INDUSTRY_NATURE_NAME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setIndustryNatureName(String industryNatureName) {
        this.industryNatureName = industryNatureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.LAST_YEAR_TURNOVER
     *
     * @return the value of cr_product_info.LAST_YEAR_TURNOVER
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Integer getLastYearTurnover() {
        return lastYearTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.LAST_YEAR_TURNOVER
     *
     * @param lastYearTurnover the value for cr_product_info.LAST_YEAR_TURNOVER
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setLastYearTurnover(Integer lastYearTurnover) {
        this.lastYearTurnover = lastYearTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.IS_PROFITABLE
     *
     * @return the value of cr_product_info.IS_PROFITABLE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Boolean getIsProfitable() {
        return isProfitable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.IS_PROFITABLE
     *
     * @param isProfitable the value for cr_product_info.IS_PROFITABLE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setIsProfitable(Boolean isProfitable) {
        this.isProfitable = isProfitable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.FINANCING
     *
     * @return the value of cr_product_info.FINANCING
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getFinancing() {
        return financing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.FINANCING
     *
     * @param financing the value for cr_product_info.FINANCING
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setFinancing(String financing) {
        this.financing = financing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.PRODUCT_VALUATION
     *
     * @return the value of cr_product_info.PRODUCT_VALUATION
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Integer getProductValuation() {
        return productValuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.PRODUCT_VALUATION
     *
     * @param productValuation the value for cr_product_info.PRODUCT_VALUATION
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setProductValuation(Integer productValuation) {
        this.productValuation = productValuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.FINANCING_PROCESS
     *
     * @return the value of cr_product_info.FINANCING_PROCESS
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getFinancingProcess() {
        return financingProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.FINANCING_PROCESS
     *
     * @param financingProcess the value for cr_product_info.FINANCING_PROCESS
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setFinancingProcess(String financingProcess) {
        this.financingProcess = financingProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.DILUTION_RATIO
     *
     * @return the value of cr_product_info.DILUTION_RATIO
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Integer getDilutionRatio() {
        return dilutionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.DILUTION_RATIO
     *
     * @param dilutionRatio the value for cr_product_info.DILUTION_RATIO
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setDilutionRatio(Integer dilutionRatio) {
        this.dilutionRatio = dilutionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.FINANCING_AMOUNT
     *
     * @return the value of cr_product_info.FINANCING_AMOUNT
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Integer getFinancingAmount() {
        return financingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.FINANCING_AMOUNT
     *
     * @param financingAmount the value for cr_product_info.FINANCING_AMOUNT
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setFinancingAmount(Integer financingAmount) {
        this.financingAmount = financingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.CREDIT_RISK
     *
     * @return the value of cr_product_info.CREDIT_RISK
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getCreditRisk() {
        return creditRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.CREDIT_RISK
     *
     * @param creditRisk the value for cr_product_info.CREDIT_RISK
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setCreditRisk(String creditRisk) {
        this.creditRisk = creditRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.BORROWING_COST
     *
     * @return the value of cr_product_info.BORROWING_COST
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getBorrowingCost() {
        return borrowingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.BORROWING_COST
     *
     * @param borrowingCost the value for cr_product_info.BORROWING_COST
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setBorrowingCost(String borrowingCost) {
        this.borrowingCost = borrowingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.BORROWING_CYCLE
     *
     * @return the value of cr_product_info.BORROWING_CYCLE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getBorrowingCycle() {
        return borrowingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.BORROWING_CYCLE
     *
     * @param borrowingCycle the value for cr_product_info.BORROWING_CYCLE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setBorrowingCycle(String borrowingCycle) {
        this.borrowingCycle = borrowingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.VERIFY_DESCRIPTION
     *
     * @return the value of cr_product_info.VERIFY_DESCRIPTION
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getVerifyDescription() {
        return verifyDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.VERIFY_DESCRIPTION
     *
     * @param verifyDescription the value for cr_product_info.VERIFY_DESCRIPTION
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setVerifyDescription(String verifyDescription) {
        this.verifyDescription = verifyDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.STATUS
     *
     * @return the value of cr_product_info.STATUS
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.STATUS
     *
     * @param status the value for cr_product_info.STATUS
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.CREATE_TIME
     *
     * @return the value of cr_product_info.CREATE_TIME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.CREATE_TIME
     *
     * @param createTime the value for cr_product_info.CREATE_TIME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.UPDATE_TIME
     *
     * @return the value of cr_product_info.UPDATE_TIME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.UPDATE_TIME
     *
     * @param updateTime the value for cr_product_info.UPDATE_TIME
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.IS_DELETE
     *
     * @return the value of cr_product_info.IS_DELETE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.IS_DELETE
     *
     * @param isDelete the value for cr_product_info.IS_DELETE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.IS_FEATURE
     *
     * @return the value of cr_product_info.IS_FEATURE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Boolean getIsFeature() {
        return isFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.IS_FEATURE
     *
     * @param isFeature the value for cr_product_info.IS_FEATURE
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setIsFeature(Boolean isFeature) {
        this.isFeature = isFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.TAGS
     *
     * @return the value of cr_product_info.TAGS
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.TAGS
     *
     * @param tags the value for cr_product_info.TAGS
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_product_info.OPERATOR
     *
     * @return the value of cr_product_info.OPERATOR
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_product_info.OPERATOR
     *
     * @param operator the value for cr_product_info.OPERATOR
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}