package com.example.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrProductInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public CrProductInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("COMPANY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("COMPANY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("COMPANY_NAME =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("COMPANY_NAME <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("COMPANY_NAME >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("COMPANY_NAME <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("COMPANY_NAME like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("COMPANY_NAME not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("COMPANY_NAME in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("COMPANY_NAME not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andImageSrcIsNull() {
            addCriterion("IMAGE_SRC is null");
            return (Criteria) this;
        }

        public Criteria andImageSrcIsNotNull() {
            addCriterion("IMAGE_SRC is not null");
            return (Criteria) this;
        }

        public Criteria andImageSrcEqualTo(String value) {
            addCriterion("IMAGE_SRC =", value, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcNotEqualTo(String value) {
            addCriterion("IMAGE_SRC <>", value, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcGreaterThan(String value) {
            addCriterion("IMAGE_SRC >", value, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcGreaterThanOrEqualTo(String value) {
            addCriterion("IMAGE_SRC >=", value, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcLessThan(String value) {
            addCriterion("IMAGE_SRC <", value, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcLessThanOrEqualTo(String value) {
            addCriterion("IMAGE_SRC <=", value, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcLike(String value) {
            addCriterion("IMAGE_SRC like", value, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcNotLike(String value) {
            addCriterion("IMAGE_SRC not like", value, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcIn(List<String> values) {
            addCriterion("IMAGE_SRC in", values, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcNotIn(List<String> values) {
            addCriterion("IMAGE_SRC not in", values, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcBetween(String value1, String value2) {
            addCriterion("IMAGE_SRC between", value1, value2, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andImageSrcNotBetween(String value1, String value2) {
            addCriterion("IMAGE_SRC not between", value1, value2, "imageSrc");
            return (Criteria) this;
        }

        public Criteria andMemberNumberIsNull() {
            addCriterion("MEMBER_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andMemberNumberIsNotNull() {
            addCriterion("MEMBER_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNumberEqualTo(String value) {
            addCriterion("MEMBER_NUMBER =", value, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberNotEqualTo(String value) {
            addCriterion("MEMBER_NUMBER <>", value, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberGreaterThan(String value) {
            addCriterion("MEMBER_NUMBER >", value, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_NUMBER >=", value, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberLessThan(String value) {
            addCriterion("MEMBER_NUMBER <", value, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_NUMBER <=", value, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberLike(String value) {
            addCriterion("MEMBER_NUMBER like", value, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberNotLike(String value) {
            addCriterion("MEMBER_NUMBER not like", value, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberIn(List<String> values) {
            addCriterion("MEMBER_NUMBER in", values, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberNotIn(List<String> values) {
            addCriterion("MEMBER_NUMBER not in", values, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberBetween(String value1, String value2) {
            addCriterion("MEMBER_NUMBER between", value1, value2, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andMemberNumberNotBetween(String value1, String value2) {
            addCriterion("MEMBER_NUMBER not between", value1, value2, "memberNumber");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("AREA is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("AREA is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("AREA =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("AREA <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("AREA >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("AREA >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("AREA <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("AREA <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("AREA like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("AREA not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("AREA in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("AREA not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("AREA between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("AREA not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeIsNull() {
            addCriterion("INDUSTRY_NATURE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeIsNotNull() {
            addCriterion("INDUSTRY_NATURE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeEqualTo(String value) {
            addCriterion("INDUSTRY_NATURE_CODE =", value, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeNotEqualTo(String value) {
            addCriterion("INDUSTRY_NATURE_CODE <>", value, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeGreaterThan(String value) {
            addCriterion("INDUSTRY_NATURE_CODE >", value, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeGreaterThanOrEqualTo(String value) {
            addCriterion("INDUSTRY_NATURE_CODE >=", value, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeLessThan(String value) {
            addCriterion("INDUSTRY_NATURE_CODE <", value, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeLessThanOrEqualTo(String value) {
            addCriterion("INDUSTRY_NATURE_CODE <=", value, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeLike(String value) {
            addCriterion("INDUSTRY_NATURE_CODE like", value, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeNotLike(String value) {
            addCriterion("INDUSTRY_NATURE_CODE not like", value, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeIn(List<String> values) {
            addCriterion("INDUSTRY_NATURE_CODE in", values, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeNotIn(List<String> values) {
            addCriterion("INDUSTRY_NATURE_CODE not in", values, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeBetween(String value1, String value2) {
            addCriterion("INDUSTRY_NATURE_CODE between", value1, value2, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureCodeNotBetween(String value1, String value2) {
            addCriterion("INDUSTRY_NATURE_CODE not between", value1, value2, "industryNatureCode");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameIsNull() {
            addCriterion("INDUSTRY_NATURE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameIsNotNull() {
            addCriterion("INDUSTRY_NATURE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameEqualTo(String value) {
            addCriterion("INDUSTRY_NATURE_NAME =", value, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameNotEqualTo(String value) {
            addCriterion("INDUSTRY_NATURE_NAME <>", value, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameGreaterThan(String value) {
            addCriterion("INDUSTRY_NATURE_NAME >", value, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameGreaterThanOrEqualTo(String value) {
            addCriterion("INDUSTRY_NATURE_NAME >=", value, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameLessThan(String value) {
            addCriterion("INDUSTRY_NATURE_NAME <", value, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameLessThanOrEqualTo(String value) {
            addCriterion("INDUSTRY_NATURE_NAME <=", value, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameLike(String value) {
            addCriterion("INDUSTRY_NATURE_NAME like", value, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameNotLike(String value) {
            addCriterion("INDUSTRY_NATURE_NAME not like", value, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameIn(List<String> values) {
            addCriterion("INDUSTRY_NATURE_NAME in", values, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameNotIn(List<String> values) {
            addCriterion("INDUSTRY_NATURE_NAME not in", values, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameBetween(String value1, String value2) {
            addCriterion("INDUSTRY_NATURE_NAME between", value1, value2, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andIndustryNatureNameNotBetween(String value1, String value2) {
            addCriterion("INDUSTRY_NATURE_NAME not between", value1, value2, "industryNatureName");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverIsNull() {
            addCriterion("LAST_YEAR_TURNOVER is null");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverIsNotNull() {
            addCriterion("LAST_YEAR_TURNOVER is not null");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverEqualTo(Integer value) {
            addCriterion("LAST_YEAR_TURNOVER =", value, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverNotEqualTo(Integer value) {
            addCriterion("LAST_YEAR_TURNOVER <>", value, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverGreaterThan(Integer value) {
            addCriterion("LAST_YEAR_TURNOVER >", value, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverGreaterThanOrEqualTo(Integer value) {
            addCriterion("LAST_YEAR_TURNOVER >=", value, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverLessThan(Integer value) {
            addCriterion("LAST_YEAR_TURNOVER <", value, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverLessThanOrEqualTo(Integer value) {
            addCriterion("LAST_YEAR_TURNOVER <=", value, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverIn(List<Integer> values) {
            addCriterion("LAST_YEAR_TURNOVER in", values, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverNotIn(List<Integer> values) {
            addCriterion("LAST_YEAR_TURNOVER not in", values, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverBetween(Integer value1, Integer value2) {
            addCriterion("LAST_YEAR_TURNOVER between", value1, value2, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andLastYearTurnoverNotBetween(Integer value1, Integer value2) {
            addCriterion("LAST_YEAR_TURNOVER not between", value1, value2, "lastYearTurnover");
            return (Criteria) this;
        }

        public Criteria andIsProfitableIsNull() {
            addCriterion("IS_PROFITABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsProfitableIsNotNull() {
            addCriterion("IS_PROFITABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsProfitableEqualTo(Boolean value) {
            addCriterion("IS_PROFITABLE =", value, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andIsProfitableNotEqualTo(Boolean value) {
            addCriterion("IS_PROFITABLE <>", value, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andIsProfitableGreaterThan(Boolean value) {
            addCriterion("IS_PROFITABLE >", value, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andIsProfitableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_PROFITABLE >=", value, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andIsProfitableLessThan(Boolean value) {
            addCriterion("IS_PROFITABLE <", value, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andIsProfitableLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_PROFITABLE <=", value, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andIsProfitableIn(List<Boolean> values) {
            addCriterion("IS_PROFITABLE in", values, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andIsProfitableNotIn(List<Boolean> values) {
            addCriterion("IS_PROFITABLE not in", values, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andIsProfitableBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_PROFITABLE between", value1, value2, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andIsProfitableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_PROFITABLE not between", value1, value2, "isProfitable");
            return (Criteria) this;
        }

        public Criteria andFinancingIsNull() {
            addCriterion("FINANCING is null");
            return (Criteria) this;
        }

        public Criteria andFinancingIsNotNull() {
            addCriterion("FINANCING is not null");
            return (Criteria) this;
        }

        public Criteria andFinancingEqualTo(String value) {
            addCriterion("FINANCING =", value, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingNotEqualTo(String value) {
            addCriterion("FINANCING <>", value, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingGreaterThan(String value) {
            addCriterion("FINANCING >", value, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingGreaterThanOrEqualTo(String value) {
            addCriterion("FINANCING >=", value, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingLessThan(String value) {
            addCriterion("FINANCING <", value, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingLessThanOrEqualTo(String value) {
            addCriterion("FINANCING <=", value, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingLike(String value) {
            addCriterion("FINANCING like", value, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingNotLike(String value) {
            addCriterion("FINANCING not like", value, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingIn(List<String> values) {
            addCriterion("FINANCING in", values, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingNotIn(List<String> values) {
            addCriterion("FINANCING not in", values, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingBetween(String value1, String value2) {
            addCriterion("FINANCING between", value1, value2, "financing");
            return (Criteria) this;
        }

        public Criteria andFinancingNotBetween(String value1, String value2) {
            addCriterion("FINANCING not between", value1, value2, "financing");
            return (Criteria) this;
        }

        public Criteria andProductValuationIsNull() {
            addCriterion("PRODUCT_VALUATION is null");
            return (Criteria) this;
        }

        public Criteria andProductValuationIsNotNull() {
            addCriterion("PRODUCT_VALUATION is not null");
            return (Criteria) this;
        }

        public Criteria andProductValuationEqualTo(Integer value) {
            addCriterion("PRODUCT_VALUATION =", value, "productValuation");
            return (Criteria) this;
        }

        public Criteria andProductValuationNotEqualTo(Integer value) {
            addCriterion("PRODUCT_VALUATION <>", value, "productValuation");
            return (Criteria) this;
        }

        public Criteria andProductValuationGreaterThan(Integer value) {
            addCriterion("PRODUCT_VALUATION >", value, "productValuation");
            return (Criteria) this;
        }

        public Criteria andProductValuationGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_VALUATION >=", value, "productValuation");
            return (Criteria) this;
        }

        public Criteria andProductValuationLessThan(Integer value) {
            addCriterion("PRODUCT_VALUATION <", value, "productValuation");
            return (Criteria) this;
        }

        public Criteria andProductValuationLessThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_VALUATION <=", value, "productValuation");
            return (Criteria) this;
        }

        public Criteria andProductValuationIn(List<Integer> values) {
            addCriterion("PRODUCT_VALUATION in", values, "productValuation");
            return (Criteria) this;
        }

        public Criteria andProductValuationNotIn(List<Integer> values) {
            addCriterion("PRODUCT_VALUATION not in", values, "productValuation");
            return (Criteria) this;
        }

        public Criteria andProductValuationBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_VALUATION between", value1, value2, "productValuation");
            return (Criteria) this;
        }

        public Criteria andProductValuationNotBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_VALUATION not between", value1, value2, "productValuation");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessIsNull() {
            addCriterion("FINANCING_PROCESS is null");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessIsNotNull() {
            addCriterion("FINANCING_PROCESS is not null");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessEqualTo(String value) {
            addCriterion("FINANCING_PROCESS =", value, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessNotEqualTo(String value) {
            addCriterion("FINANCING_PROCESS <>", value, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessGreaterThan(String value) {
            addCriterion("FINANCING_PROCESS >", value, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessGreaterThanOrEqualTo(String value) {
            addCriterion("FINANCING_PROCESS >=", value, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessLessThan(String value) {
            addCriterion("FINANCING_PROCESS <", value, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessLessThanOrEqualTo(String value) {
            addCriterion("FINANCING_PROCESS <=", value, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessLike(String value) {
            addCriterion("FINANCING_PROCESS like", value, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessNotLike(String value) {
            addCriterion("FINANCING_PROCESS not like", value, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessIn(List<String> values) {
            addCriterion("FINANCING_PROCESS in", values, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessNotIn(List<String> values) {
            addCriterion("FINANCING_PROCESS not in", values, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessBetween(String value1, String value2) {
            addCriterion("FINANCING_PROCESS between", value1, value2, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andFinancingProcessNotBetween(String value1, String value2) {
            addCriterion("FINANCING_PROCESS not between", value1, value2, "financingProcess");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioIsNull() {
            addCriterion("DILUTION_RATIO is null");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioIsNotNull() {
            addCriterion("DILUTION_RATIO is not null");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioEqualTo(Integer value) {
            addCriterion("DILUTION_RATIO =", value, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioNotEqualTo(Integer value) {
            addCriterion("DILUTION_RATIO <>", value, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioGreaterThan(Integer value) {
            addCriterion("DILUTION_RATIO >", value, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioGreaterThanOrEqualTo(Integer value) {
            addCriterion("DILUTION_RATIO >=", value, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioLessThan(Integer value) {
            addCriterion("DILUTION_RATIO <", value, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioLessThanOrEqualTo(Integer value) {
            addCriterion("DILUTION_RATIO <=", value, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioIn(List<Integer> values) {
            addCriterion("DILUTION_RATIO in", values, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioNotIn(List<Integer> values) {
            addCriterion("DILUTION_RATIO not in", values, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioBetween(Integer value1, Integer value2) {
            addCriterion("DILUTION_RATIO between", value1, value2, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andDilutionRatioNotBetween(Integer value1, Integer value2) {
            addCriterion("DILUTION_RATIO not between", value1, value2, "dilutionRatio");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountIsNull() {
            addCriterion("FINANCING_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountIsNotNull() {
            addCriterion("FINANCING_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountEqualTo(Integer value) {
            addCriterion("FINANCING_AMOUNT =", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountNotEqualTo(Integer value) {
            addCriterion("FINANCING_AMOUNT <>", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountGreaterThan(Integer value) {
            addCriterion("FINANCING_AMOUNT >", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("FINANCING_AMOUNT >=", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountLessThan(Integer value) {
            addCriterion("FINANCING_AMOUNT <", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountLessThanOrEqualTo(Integer value) {
            addCriterion("FINANCING_AMOUNT <=", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountIn(List<Integer> values) {
            addCriterion("FINANCING_AMOUNT in", values, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountNotIn(List<Integer> values) {
            addCriterion("FINANCING_AMOUNT not in", values, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountBetween(Integer value1, Integer value2) {
            addCriterion("FINANCING_AMOUNT between", value1, value2, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("FINANCING_AMOUNT not between", value1, value2, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andCreditRiskIsNull() {
            addCriterion("CREDIT_RISK is null");
            return (Criteria) this;
        }

        public Criteria andCreditRiskIsNotNull() {
            addCriterion("CREDIT_RISK is not null");
            return (Criteria) this;
        }

        public Criteria andCreditRiskEqualTo(String value) {
            addCriterion("CREDIT_RISK =", value, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskNotEqualTo(String value) {
            addCriterion("CREDIT_RISK <>", value, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskGreaterThan(String value) {
            addCriterion("CREDIT_RISK >", value, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskGreaterThanOrEqualTo(String value) {
            addCriterion("CREDIT_RISK >=", value, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskLessThan(String value) {
            addCriterion("CREDIT_RISK <", value, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskLessThanOrEqualTo(String value) {
            addCriterion("CREDIT_RISK <=", value, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskLike(String value) {
            addCriterion("CREDIT_RISK like", value, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskNotLike(String value) {
            addCriterion("CREDIT_RISK not like", value, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskIn(List<String> values) {
            addCriterion("CREDIT_RISK in", values, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskNotIn(List<String> values) {
            addCriterion("CREDIT_RISK not in", values, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskBetween(String value1, String value2) {
            addCriterion("CREDIT_RISK between", value1, value2, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andCreditRiskNotBetween(String value1, String value2) {
            addCriterion("CREDIT_RISK not between", value1, value2, "creditRisk");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostIsNull() {
            addCriterion("BORROWING_COST is null");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostIsNotNull() {
            addCriterion("BORROWING_COST is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostEqualTo(String value) {
            addCriterion("BORROWING_COST =", value, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostNotEqualTo(String value) {
            addCriterion("BORROWING_COST <>", value, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostGreaterThan(String value) {
            addCriterion("BORROWING_COST >", value, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostGreaterThanOrEqualTo(String value) {
            addCriterion("BORROWING_COST >=", value, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostLessThan(String value) {
            addCriterion("BORROWING_COST <", value, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostLessThanOrEqualTo(String value) {
            addCriterion("BORROWING_COST <=", value, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostLike(String value) {
            addCriterion("BORROWING_COST like", value, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostNotLike(String value) {
            addCriterion("BORROWING_COST not like", value, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostIn(List<String> values) {
            addCriterion("BORROWING_COST in", values, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostNotIn(List<String> values) {
            addCriterion("BORROWING_COST not in", values, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostBetween(String value1, String value2) {
            addCriterion("BORROWING_COST between", value1, value2, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCostNotBetween(String value1, String value2) {
            addCriterion("BORROWING_COST not between", value1, value2, "borrowingCost");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleIsNull() {
            addCriterion("BORROWING_CYCLE is null");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleIsNotNull() {
            addCriterion("BORROWING_CYCLE is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleEqualTo(String value) {
            addCriterion("BORROWING_CYCLE =", value, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleNotEqualTo(String value) {
            addCriterion("BORROWING_CYCLE <>", value, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleGreaterThan(String value) {
            addCriterion("BORROWING_CYCLE >", value, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleGreaterThanOrEqualTo(String value) {
            addCriterion("BORROWING_CYCLE >=", value, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleLessThan(String value) {
            addCriterion("BORROWING_CYCLE <", value, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleLessThanOrEqualTo(String value) {
            addCriterion("BORROWING_CYCLE <=", value, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleLike(String value) {
            addCriterion("BORROWING_CYCLE like", value, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleNotLike(String value) {
            addCriterion("BORROWING_CYCLE not like", value, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleIn(List<String> values) {
            addCriterion("BORROWING_CYCLE in", values, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleNotIn(List<String> values) {
            addCriterion("BORROWING_CYCLE not in", values, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleBetween(String value1, String value2) {
            addCriterion("BORROWING_CYCLE between", value1, value2, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andBorrowingCycleNotBetween(String value1, String value2) {
            addCriterion("BORROWING_CYCLE not between", value1, value2, "borrowingCycle");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionIsNull() {
            addCriterion("VERIFY_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionIsNotNull() {
            addCriterion("VERIFY_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionEqualTo(String value) {
            addCriterion("VERIFY_DESCRIPTION =", value, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionNotEqualTo(String value) {
            addCriterion("VERIFY_DESCRIPTION <>", value, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionGreaterThan(String value) {
            addCriterion("VERIFY_DESCRIPTION >", value, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_DESCRIPTION >=", value, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionLessThan(String value) {
            addCriterion("VERIFY_DESCRIPTION <", value, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionLessThanOrEqualTo(String value) {
            addCriterion("VERIFY_DESCRIPTION <=", value, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionLike(String value) {
            addCriterion("VERIFY_DESCRIPTION like", value, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionNotLike(String value) {
            addCriterion("VERIFY_DESCRIPTION not like", value, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionIn(List<String> values) {
            addCriterion("VERIFY_DESCRIPTION in", values, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionNotIn(List<String> values) {
            addCriterion("VERIFY_DESCRIPTION not in", values, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionBetween(String value1, String value2) {
            addCriterion("VERIFY_DESCRIPTION between", value1, value2, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andVerifyDescriptionNotBetween(String value1, String value2) {
            addCriterion("VERIFY_DESCRIPTION not between", value1, value2, "verifyDescription");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("IS_DELETE =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("IS_DELETE <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("IS_DELETE >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_DELETE >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("IS_DELETE <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_DELETE <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("IS_DELETE in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("IS_DELETE not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_DELETE between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_DELETE not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsFeatureIsNull() {
            addCriterion("IS_FEATURE is null");
            return (Criteria) this;
        }

        public Criteria andIsFeatureIsNotNull() {
            addCriterion("IS_FEATURE is not null");
            return (Criteria) this;
        }

        public Criteria andIsFeatureEqualTo(Boolean value) {
            addCriterion("IS_FEATURE =", value, "isFeature");
            return (Criteria) this;
        }

        public Criteria andIsFeatureNotEqualTo(Boolean value) {
            addCriterion("IS_FEATURE <>", value, "isFeature");
            return (Criteria) this;
        }

        public Criteria andIsFeatureGreaterThan(Boolean value) {
            addCriterion("IS_FEATURE >", value, "isFeature");
            return (Criteria) this;
        }

        public Criteria andIsFeatureGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_FEATURE >=", value, "isFeature");
            return (Criteria) this;
        }

        public Criteria andIsFeatureLessThan(Boolean value) {
            addCriterion("IS_FEATURE <", value, "isFeature");
            return (Criteria) this;
        }

        public Criteria andIsFeatureLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_FEATURE <=", value, "isFeature");
            return (Criteria) this;
        }

        public Criteria andIsFeatureIn(List<Boolean> values) {
            addCriterion("IS_FEATURE in", values, "isFeature");
            return (Criteria) this;
        }

        public Criteria andIsFeatureNotIn(List<Boolean> values) {
            addCriterion("IS_FEATURE not in", values, "isFeature");
            return (Criteria) this;
        }

        public Criteria andIsFeatureBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_FEATURE between", value1, value2, "isFeature");
            return (Criteria) this;
        }

        public Criteria andIsFeatureNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_FEATURE not between", value1, value2, "isFeature");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("TAGS is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("TAGS is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("TAGS =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("TAGS <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("TAGS >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("TAGS >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("TAGS <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("TAGS <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("TAGS like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("TAGS not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("TAGS in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("TAGS not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("TAGS between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("TAGS not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("OPERATOR =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("OPERATOR <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("OPERATOR >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATOR >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("OPERATOR <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("OPERATOR <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("OPERATOR like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("OPERATOR not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("OPERATOR in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("OPERATOR not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("OPERATOR between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("OPERATOR not between", value1, value2, "operator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_product_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 26 11:03:23 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}