package com.example.demo.entity;

import lombok.Data;

import java.util.Date;

/**
 * undo_log
 * 
 * @author bianj
 * @version 1.0.0 2021-04-28
 */
@Data
public class UndoLog implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1203608262447781887L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Long id;

    /** branchId */
    private Long branchId;

    /** xid */
    private String xid;

    /** context */
    private String context;

    /** rollbackInfo */
    private Byte[] rollbackInfo;

    /** logStatus */
    private Integer logStatus;

    /** logCreated */
    private Date logCreated;

    /** logModified */
    private Date logModified;

    /** ext */
    private String ext;

}