package com.example.demo.entity;

import com.alibaba.excel.annotation.ExcelProperty;
import lombok.Data;
import lombok.Value;

import java.sql.Timestamp;
import java.util.Date;

/**
 * user_test_time
 * 
 * @author bianj
 * @version 1.0.0 2021-04-28
 */
@Data
public class UserTestTime implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4440248740405052439L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Long id;

    /** username */
    @ExcelProperty(value = "用户名")
    private String username;

    /** rearName */
    @ExcelProperty(value = "真实姓名")
    private String rearName;

    /** password */
    @ExcelProperty(value = "密码")
    private String password;

    /** createTime */
    @ExcelProperty(value = "创建时间")
    private Date createTime;

    /** createTimeStamp */
    private Timestamp createTimeStamp;

    /** updateTime */
    private Date updateTime;

    /** updateTimeStamp */
    private Timestamp updateTimeStamp;

    /** testTime */
    private Date testTime;

    /** testStamp */
    private Timestamp testStamp;

    /** isDelete */
    private Integer isDelete;

}