package com.example.demo.mapper;

import com.example.demo.entity.CrProductInfo;
import com.example.demo.entity.CrProductInfoExample;
import com.example.demo.entity.CrProductInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    long countByExample(CrProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int deleteByExample(CrProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int insert(CrProductInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int insertSelective(CrProductInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    List<CrProductInfoWithBLOBs> selectByExampleWithBLOBs(CrProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    List<CrProductInfo> selectByExample(CrProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    CrProductInfoWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") CrProductInfoWithBLOBs record, @Param("example") CrProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") CrProductInfoWithBLOBs record, @Param("example") CrProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int updateByExample(@Param("record") CrProductInfo record, @Param("example") CrProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int updateByPrimaryKeySelective(CrProductInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(CrProductInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_product_info
     *
     * @mbg.generated Sun Apr 26 11:03:23 CST 2020
     */
    int updateByPrimaryKey(CrProductInfo record);
}